### ISSUE TITLE
package.json expresses nomnom 1.0.x dep, but programs against more recent API

### ISSUE THREAD

**Issue by asutherland** [harthur/replace#1]
nomnom.options is apparently not a thing in 1.0.x and so attempts to use bin/replace.js fail.  But if I relax the package.json to 1.x and then force an upgrade and get 1.5, things seem to work.  I'm not sure what dep you would want, so no pull request.

Thanks for the great tool!  Batch replacing has always been one of my command-line nightmares and my sed-fu is weak.

**Comment by niftylettuce** [comment]
Feel free to use my module instead:

``` bash
npm install -g niftylettuce-replace
```

**Comment by niftylettuce** [comment]
Link to repo: https://github.com/niftylettuce/replace

**Comment by harthur** [comment]
Fixed, sorry!
