### ISSUE TITLE
Confirm flag

### ISSUE THREAD

**Issue by tmcw** [harthur/replace#38]
Would love to have something like vim's `/gc` mode in which `replace` would ask whether to replace each segment and get a `y/n` answer. I'm game to implement this if it's desirable.

**Comment by harthur** [comment]
Yep, this would be amazing. I tried using node's `readLine` (maybe? it was a couple years ago) with an async flow library, but I got some error for too many nested calls. Might be doable with new interface though: http://nodejs.org/api/readline.html

**Comment by tmcw** [comment]
Sorry, I probably won't get the time to implement this.
