### ISSUE TITLE
awesome utility, but...

### ISSUE THREAD

**Issue by getify** [harthur/replace#7]
This is great, and a huge help.

But please, oh please, for the love of all things good and right in this world, don't use "replace 'var' with 'let' in JS files" as your primary examples. "Let is the new var" is one very dangerous piece of misinformation that is starting to spread, and any time I see it, it makes me want to throw up a little in my mouth. :)

**Comment by harthur** [comment]
Hm, I really don't think it's propaganda for `let`, I was just using a real-life example that I'd used in writing Mozilla code. But, I'll take this into consideration if I come up with another example.

**Comment by getify** [comment]
I know @dherman and @rwldrn (both on TC39) can elaborate more on this topic, but I wouldn't at all consider it a safe practice to just blindly replace every `var` with `let`, because there are plenty of cases where `var` can appear that replacing it with `let` will actually change the behavior of the program (like when `var` shows up inside an `if` block, etc). When `let` finally lands in the wider JS (not just in Mozilla's specific browser JS -- which is quite nice to play exclusively in!), I think there will have to be careful and considered refactoring.

All this is way overblowing things, and I'm sorry for that! I really just meant it as a side comment more than a serious problem. I love the utility. But I do think it's important to point out potential "bad practices" where they can be seen. I'd hate for even one developer to think that "replace all 'var' with 'let' statements" was an endorsed best practice for the wider web.

**Comment by rwaldron** [comment]
I've gone on record many times, stating publicly that "Let is the new var" is irresponsible evangelism. `let` semantics aren't even completely specified, especially with regard to temporal deadzone behaviors (of which there are 3 possibilities) at initialization and assignment. 

Sure, most `var` uses can be replaced with `let`, but not blindly and not without understanding the semantics shift.

**Comment by carlthewebmaster** [comment]
Why not change the example to one that replaces "foo" with "bar"?  Having a controversial example (whichever side of the controversy one may choose including abstention) doesn't add to the value of the example.  It's not like it's hard to change the readme.md.  Just a thought.

**Comment by harthur** [comment]
@getify and @rwldrn, thanks, I see your point. @carlthewebmaster, I haven't quite gotten around to changing this, but I'll do so very soon.

**Comment by carlthewebmaster** [comment]
:)

**Comment by getify** [comment]
<3. and again, @harthur, really sorry that my comments came across as negative at first. seeing what else those other idiots were piling on you in twitterland makes me sad I posted this issue when I did.

**Comment by benatkin** [comment]
I like the var and let example, even if it might be harmful in some contexts. If it's going to be replaced it should be replaced with something equally javascripty. I am so very tired of foo and bar.

**Comment by harthur** [comment]
@getify it's okay, I did not feel your comments were attacking.

I merged a pull request that replaced em with old foo and bar, until someone can think of a better example.

**Comment by getify** [comment]
3 cheers! <3

**Comment by rwaldron** [comment]
@harthur  apparently I was living in a vacuum for most of this week because I was completely unaware of the HN thread until late last night.  Additionally, when I originally responded to being cc'ed here, I did so from my iPhone and actually didn't know who user "harthur" was at all (until last night). Anyway, the point is that my response was given  independently of any HN douche-baggery.

But seriously, fuck them. JavaScript all the things :+1:

**Comment by harthur** [comment]
@getify @rwldrn don't worry, you're fine. Thanks for reporting, I agree with it.
