### ISSUE TITLE
replace -h

### ISSUE THREAD

**Issue by cistov** [harthur/replace#8]
replace -h does not seem to print out options as suggested in the readme (search -h is fine)?

node v0.6.14

**Comment by harthur** [comment]
Hm, I can't reproduce this unfortunately, I'm on node v0.6.18. It might be the option parser dependency however. Can you paste the output of `npm ls --global` here (or just the `replace` section), so I can see what version you're using?

**Comment by cistov** [comment]
Hm, I've reinstalled it & it's fine now. Can't reproduce this anymore. Thanks.
